version: '2'

services:
  database:
    image: postgres
    env_file:
        - .env
    volumes:
        - ./dbdata:/var/lib/postgresql/data
    env_file:
        - .env

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=redis
    env_file:
      - .env

  web:
    build: ./
    depends_on:
      - "database"
      - "redis"
    command: bash -c "python3 manage.py collectstatic --noinput &&
                      python3 manage.py makemigrations &&
                      python3 manage.py migrate &&
                      python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./static:/opt/public/static
      - ./src:/opt/office-manager
    ports:
     - "80:8000"
